const CATEGORIES = ["COMPANY", "HR", "ENGINEERING", "IT", "OPERATIONS", "EVENTS"]

const STATUSES = ["DRAFT", "PUBLISHED", "ARCHIVED"]

const DEFAULT_PAGE_SIZE = 20

module.exports = { CATEGORIES, STATUSES, DEFAULT_PAGE_SIZE }
